application: kv35family
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /static/images/(.*)
  static_files: static/images/\1
  upload: static/images/(.*)
  
- url: /static/stylesheets
  static_dir: static/stylesheets/css
  
- url: /static/javascripts
  static_dir: static/javascripts

- url: .*
  script: main.app


libraries:
- name: webapp2
  version: "2.5.1"
- name: jinja2
  version: latest
